// The 25 people of the simulated demo season. Each seed is a sketch; the
// generator turns it into full LinkedIn + Instagram content and photos.
// Every person here is fictional.

export type Seed = {
  slug: string;
  name: string;
  pronouns: "she/her" | "he/him";
  age: number;
  city: string;
  role: string;
  hobbies: string[];
  vibe: string;
  look: string; // for the illustrated avatar only
};

export const SEEDS: Seed[] = [
  { slug: "aanya-kapoor", name: "Aanya Kapoor", pronouns: "she/her", age: 27, city: "Bengaluru", role: "Product designer at a consumer fintech startup", hobbies: ["wheel pottery at a studio in Indiranagar", "very slow long-distance running", "sketching in cafés"], vibe: "calm, dry humour, hosts small dinners, likes things imperfect and handmade", look: "shoulder-length wavy hair, round glasses, linen shirt" },
  { slug: "kabir-mehta", name: "Kabir Mehta", pronouns: "he/him", age: 29, city: "Bengaluru", role: "Backend engineer at a payments company", hobbies: ["indoor bouldering", "baking sourdough (badly, persistently)", "monsoon treks in the Western Ghats"], vibe: "nerdy, self-deprecating, mentors juniors, likes long walks with no destination", look: "short curly hair, stubble, grey t-shirt" },
  { slug: "meera-iyer", name: "Meera Iyer", pronouns: "she/her", age: 31, city: "Mumbai", role: "Co-founder of a carbon-accounting startup for small factories (ex-consultant)", hobbies: ["hosting a 6-person book club", "evening walks on Carter Road", "visiting factories she works with"], vibe: "driven, warm, practical, believes small boring changes beat big promises", look: "long straight hair tied back, small gold earrings, blazer" },
  { slug: "rohan-desai", name: "Rohan Desai", pronouns: "he/him", age: 30, city: "Mumbai", role: "Data scientist building cricket win-probability models for a sports analytics firm", hobbies: ["8 years of tabla", "cooking biryani for big groups", "going to Wankhede for T20s"], vibe: "funny, numbers guy, generous host, early riser", look: "neat beard, kurta, warm smile" },
  { slug: "ishita-banerjee", name: "Ishita Banerjee", pronouns: "she/her", age: 26, city: "Kolkata", role: "Features journalist at a regional daily", hobbies: ["street photography on film", "singing Rabindrasangeet", "long addas at College Street coffee house"], vibe: "curious, opinionated, romantic about old cities, asks too many questions", look: "short bob, kohl eyes, cotton saree with a denim jacket" },
  { slug: "arjun-nair", name: "Arjun Nair", pronouns: "he/him", age: 33, city: "Kochi", role: "Marine biologist running a coastal reef-restoration project", hobbies: ["scuba diving", "sea kayaking", "watching Kathakali performances"], vibe: "quiet, patient, outdoorsy, happiest near water", look: "sun-tanned, wavy hair, field vest" },
  { slug: "zoya-sheikh", name: "Zoya Sheikh", pronouns: "she/her", age: 28, city: "Hyderabad", role: "Paediatrics resident doctor", hobbies: ["baking elaborate cakes on rare days off", "reading and writing Urdu poetry", "weekend badminton"], vibe: "caring, permanently a little tired, sharp wit, loyal to her people", look: "hair in a loose braid, scrubs under a cardigan" },
  { slug: "vikram-rathore", name: "Vikram Rathore", pronouns: "he/him", age: 34, city: "Jaipur", role: "Conservation architect restoring old havelis", hobbies: ["heritage walks he leads for free", "ink sketching of facades", "horse riding at a family stable"], vibe: "old soul, courteous, slow and deliberate, loves craftspeople", look: "salt-and-pepper short hair, round spectacles, bandhgala" },
  { slug: "tara-menon", name: "Tara Menon", pronouns: "she/her", age: 25, city: "Pune", role: "UX researcher at an edtech company", hobbies: ["salsa social nights", "board game cafés", "volunteering at an animal shelter on Sundays"], vibe: "bubbly, social, competitive at board games, soft spot for senior dogs", look: "high ponytail, bright earrings, striped top" },
  { slug: "siddharth-rao", name: "Siddharth Rao", pronouns: "he/him", age: 32, city: "Bengaluru", role: "Machine learning engineer at a healthtech startup", hobbies: ["trail running and 50k ultras", "building mechanical keyboards", "playing Carnatic violin"], vibe: "intense but gentle, disciplined mornings, quietly funny", look: "lean, buzz cut, running cap" },
  { slug: "neha-gupta", name: "Neha Gupta", pronouns: "she/her", age: 30, city: "Delhi", role: "Corporate lawyer at a mid-size firm", hobbies: ["amateur theatre with a Hindi-English troupe", "Old Delhi food walks", "online blitz chess"], vibe: "sharp, fast-talking, theatrical, fiercely loyal, works long weeks", look: "sleek bob, statement earrings, black kurta" },
  { slug: "aditya-verma", name: "Aditya Verma", pronouns: "he/him", age: 27, city: "Delhi", role: "Indie musician and part-time guitar teacher", hobbies: ["playing open mics in Hauz Khas", "cycling at dawn around Lodhi Garden", "writing songs in a notebook"], vibe: "dreamy, playful, irregular schedule, notices small things", look: "messy hair, silver ring, denim jacket" },
  { slug: "priya-raghavan", name: "Priya Raghavan", pronouns: "she/her", age: 29, city: "Chennai", role: "Data analyst at a bank", hobbies: ["Bharatanatyam since childhood", "December Margazhi concert season", "beach runs at Besant Nagar"], vibe: "disciplined, sweet, rooted in family, secretly loves horror films", look: "long braid with jasmine, small bindi, cotton kurta" },
  { slug: "kunal-joshi", name: "Kunal Joshi", pronouns: "he/him", age: 31, city: "Pune", role: "Chef-owner of a small Goan-Maharashtrian restaurant", hobbies: ["early-morning market runs", "motorbike trips to the Konkan coast", "collecting old vinyl"], vibe: "generous, loud, feeds everyone, works late nights", look: "bandana, tattooed forearms, chef's apron" },
  { slug: "riya-sen", name: "Riya Sen", pronouns: "she/her", age: 24, city: "Bengaluru", role: "Associate product manager at a food-delivery company (moved from Kolkata)", hobbies: ["performing at stand-up comedy open mics", "thrift shopping", "K-drama marathons"], vibe: "chaotic, very funny, self-roasting, homesick for Kolkata food", look: "curtain bangs, oversized thrifted blazer" },
  { slug: "farhan-qureshi", name: "Farhan Qureshi", pronouns: "he/him", age: 35, city: "Mumbai", role: "Documentary filmmaker", hobbies: ["film photography", "long train journeys across India", "chai crawls in old neighbourhoods"], vibe: "reflective, good listener, travels for shoots, collects stories", look: "short beard, flat cap, camera strap" },
  { slug: "ananya-krishnan", name: "Ananya Krishnan", pronouns: "she/her", age: 32, city: "Bengaluru", role: "Climate policy researcher at a think tank", hobbies: ["birding at lakes before sunrise", "a terrace vegetable garden", "Himalayan treks"], vibe: "earnest, curious, a little nerdy, early to bed and early up", look: "short natural hair, binoculars around neck, khadi shirt" },
  { slug: "dev-malhotra", name: "Dev Malhotra", pronouns: "he/him", age: 28, city: "Gurugram", role: "Management consultant", hobbies: ["marathon training", "Formula 1", "cooking pasta from scratch"], vibe: "ambitious, energetic, travels Monday to Thursday, wants to slow down eventually", look: "clean-cut, quarter-zip sweater, sports watch" },
  { slug: "sana-mirza", name: "Sana Mirza", pronouns: "she/her", age: 27, city: "Delhi", role: "Founder-designer of a small sustainable clothing label", hobbies: ["block-printing workshops in Rajasthan", "vintage markets", "Bollywood dance classes"], vibe: "vibrant, creative, entrepreneurial, close to her artisans", look: "dramatic winged eyeliner, block-printed dupatta" },
  { slug: "rahul-pillai", name: "Rahul Pillai", pronouns: "he/him", age: 30, city: "Chennai", role: "Commercial airline first officer", hobbies: ["open-water swimming", "stargazing with a telescope", "cooking Kerala food his grandmother taught him"], vibe: "calm, steady, irregular rosters, loves quiet nights", look: "close-cropped hair, aviator sunglasses pushed up, white shirt" },
  { slug: "kavya-shetty", name: "Kavya Shetty", pronouns: "she/her", age: 26, city: "Bengaluru", role: "Physiotherapist and weekend yoga teacher", hobbies: ["surfing at Mulki on long weekends", "cooking Mangalorean food", "reading memoirs"], vibe: "grounded, outdoorsy, gentle humour, early riser", look: "sun-streaked hair, tank top, shell necklace" },
  { slug: "nikhil-bhatia", name: "Nikhil Bhatia", pronouns: "he/him", age: 29, city: "Bengaluru", role: "Game developer at an indie studio", hobbies: ["designing his own board games", "anime", "rock climbing at a gym"], vibe: "playful introvert, puzzle brain, warms up slowly then never stops talking", look: "hoodie, headphones around neck, glasses" },
  { slug: "ira-deshpande", name: "Ira Deshpande", pronouns: "she/her", age: 33, city: "Mumbai", role: "Former investment banker who now runs her own bakery", hobbies: ["marathon running", "Marathi theatre", "fostering rescue dogs"], vibe: "resilient, direct, hard-working, softie about dogs", look: "messy bun, flour on her apron, gold hoops" },
  { slug: "aman-sethi", name: "Aman Sethi", pronouns: "he/him", age: 26, city: "Chandigarh", role: "High-school maths teacher and YouTube maths tutor", hobbies: ["coaching a kids' football team", "Punjabi folk music", "road trips to Himachal"], vibe: "earnest, encouraging, family-oriented, big laugh", look: "turban, neatly trimmed beard, football jersey" },
  { slug: "lavanya-reddy", name: "Lavanya Reddy", pronouns: "she/her", age: 30, city: "Hyderabad", role: "Founder of an agritech startup for women farmers", hobbies: ["weekend treks", "Telugu cinema first-day-first-shows", "making pickles with her grandmother"], vibe: "energetic, mission-driven, rooted, laughs loudly", look: "short hair, cotton saree with sneakers" },
];
